name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: download googletest lib
          run: |
            mkdir lib
            git clone https://github.com/google/googletest/ lib
        - name: cmake
          run: |
            mkdir -p build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"
        - name: make test
          run: cd build && make CiCdTest_tst && test/CiCdTest_tst